
export const ALARM_CANDIDATES = {
  S1: [
    {name: '合角度', field: 'hypotenuse'},
    {name: '合角度变化速率', field: 'hypotenuseVelocity'},
  ],
  S2: [
    {name: '角度', field: 'xFinal'},
    {name: '角度变化速率', field: 'xVelocity'},
  ],
  S3: [
    {name: 'X角度', field: 'xFinal'},
    {name: 'Y角度', field: 'yFinal'},
    {name: '合角度', field: 'hypotenuse'},
    {name: '合角度变化速率', field: 'hypotenuseVelocity'},
  ],
  D1: [
    {name: '合位移', field: 'hDisplacement'},
    {name: '合位移变化速率', field: 'hDisplacementVelocity'},
  ],
  D2: [
    {name: '位移', field: 'xDisplacement'},
    {name: '位移变化速率', field: 'xDisplacementVelocity'},
  ],
  D3: [
    {name: '合位移', field: 'hDisplacement'},
    {name: '合位移变化速率', field: 'hDisplacementVelocity'},
  ],
  I1: [
    {name: '倾斜度', field: 'hGradientInclination'},
    {name: '倾斜度变化速率', field: 'hGradientInclinationVelocity'},
  ],
  I2: [
    {name: '倾斜度', field: 'hGradientInclination'},
    {name: '倾斜度变化速率', field: 'hGradientInclinationVelocity'},
  ],
  I3: [
    {name: '倾斜度', field: 'hGradientInclination'},
    {name: '倾斜度变化速率', field: 'hGradientInclinationVelocity'},
  ],
  I4: [
    {name: '合角度', field: 'hypotenuse'},
    {name: '合角度变化速率', field: 'hypotenuseVelocity'},
    {name: '合位移', field: 'hDisplacement'},
    {name: '合位移变化速率', field: 'hDisplacementVelocity'},
    {name: '沉降位移', field: 'sedimentation'},
    {name: '沉降位移变化速率', field: 'sedimentationVelocity'},
  ],
  H1: [
    {name: 'x方向累计位移', field: 'xAccumulateDisplacement'},
    {name: 'Y方向累计位移', field: 'yAccumulateDisplacement'},
    {name: 'x方向累计位移速率', field: 'xDisplacementVelocity'},
    {name: 'Y方向累计位移速率', field: 'yDisplacementVelocity'},
    {name: '累计合位移', field: 'hAccumulateDisplacement'},
    {name: '累计合位移速率', field: 'hDisplacementVelocity'},
  ],
  SG: [
    // {name: 'X角度', field: 'xFinal'},
    // {name: 'Y角度', field: 'yFinal'},
    {name: 'x方向最终位移', field: 'xDisplacement'},
    {name: 'Y方向最终位移', field: 'yDisplacement'},
    // {name: 'x方向累计位移速率', field: 'xDisplacementVelocity'},
    // {name: 'Y方向累计位移速率', field: 'yDisplacementVelocity'},
  ],
  MD1: [
    {name: '累计变形值', field: 'accumulate'},
    {name: '变化速率', field: 'velocity'},
  ],
  MH2: [
    {name: '累计变形值', field: 'accumulate'},
    {name: '变化速率', field: 'velocity'},
    // {name: 'x方向累计位移', field: 'accumulate'},
    // {name: 'Y方向累计位移', field: 'accumulate'},
    // {name: 'x方向累计位移速率', field: 'accumulate'},
    // {name: 'Y方向累计位移速率', field: 'accumulate'},
    // {name: '累计合位移', field: 'accumulate'},
    // {name: '累计合位移速率', field: 'accumulate'},
  ],
  MVM: [
    {name: '累计变形值', field: 'accumulate'},
    {name: '变化速率', field: 'velocity'},
  ],
  AICM: [
    {name: '累计变形值', field: 'measureValue'},
    {name: '变化速率', field: 'velocity'},
  ],
}

// 连续n天平均速度、单日最大变化量、单次最大变化量、累计变化值、连续n小时（采集频率的倍数）每次累积变化值 改为 连续n小时累积变化量

export const ALARM_TYPES = {
  S1: {
    S1A1: {name: '连续n天平均速度', unit: '°/d'},
    S1A2: {name: '单日最大变化量', unit: '°'},
    S1A3: {name: '单次最大变化量', unit: '°'},
    S1A4: {name: '累计变化值', unit: '°'},
    S1A5: {name: '连续n小时累积变化量', unit: '°'},
  },
  S2: {
    S2A1: {name: '连续n天平均速度', unit: '°/d'},
    S2A2: {name: '单日最大变化量', unit: '°'},
    S2A3: {name: '单次最大变化量', unit: '°'},
    S2A4: {name: '累计变化值', unit: '°'},
    S2A5: {name: '连续n小时累积变化量', unit: '°'},
  },
  S3: {
    S1A1: {name: '连续n天平均速度', unit: '°/d'},
    S1A2: {name: '单日最大变化量', unit: '°'},
    S1A3: {name: '单次最大变化量', unit: '°'},
    S1A4: {name: '累计变化值', unit: '°'},
    S1A5: {name: '连续n小时累积变化量', unit: '°'},
  },
  D1: {
    D1A1: {name: '连续n天平均速度', unit: 'mm/d'},
    D1A2: {name: '单日最大变化量', unit: 'mm'},
    D1A3: {name: '单次最大变化量', unit: 'mm'},
    D1A4: {name: '累计变化值', unit: 'mm'},
    D1A5: {name: '连续n小时累积变化量', unit: 'mm'},
  },
  D2: {
    D2A1: {name: '连续n天平均速度', unit: 'mm/d'},
    D2A2: {name: '单日最大变化量', unit: 'mm'},
    D2A3: {name: '单次最大变化量', unit: 'mm'},
    D2A4: {name: '累计变化值', unit: 'mm'},
    D2A5: {name: '连续n小时累积变化量', unit: 'mm'},
  },
  D3: {
    D3A1: {name: '连续n天平均速度', unit: 'mm/d'},
    D3A2: {name: '单日最大变化量', unit: 'mm'},
    D3A3: {name: '单次最大变化量', unit: 'mm'},
    D3A4: {name: '累计变化值', unit: 'mm'},
    D3A5: {name: '连续n小时累积变化量', unit: 'mm'},
  },
  I1: {
    I1A1: {name: '连续n天平均速度', unit: 'mm/m/d'},
    I1A2: {name: '单日最大变化量', unit: 'mm/m'},
    I1A3: {name: '单次最大变化量', unit: 'mm/m'},
    I1A4: {name: '累计变化值', unit: 'mm/m'},
    I1A5: {name: '连续n小时累积变化量', unit: 'mm/m'},
  },
  I2: {
    I2A1: {name: '连续n天平均速度', unit: 'mm/m/d'},
    I2A2: {name: '单日最大变化量', unit: 'mm/m'},
    I2A3: {name: '单次最大变化量', unit: 'mm/m'},
    I2A4: {name: '累计变化值', unit: 'mm/m'},
    I2A5: {name: '连续n小时累积变化量', unit: 'mm/m'},
  },
  I3: {
    I3A1: {name: '连续n天平均速度', unit: 'mm/m/d'},
    I3A2: {name: '单日最大变化量', unit: 'mm/m'},
    I3A3: {name: '单次最大变化量', unit: 'mm/m'},
    I3A4: {name: '累计变化值', unit: 'mm/m'},
    I3A5: {name: '连续n小时累积变化量', unit: 'mm/m'},
  },
  I4: {
    I4A1: {name: '连续n天平均速度', unit: 'mm/m/d'},
    I4A2: {name: '单日最大变化量', unit: 'mm/m'},
    I4A3: {name: '单次最大变化量', unit: 'mm/m'},
    I4A4: {name: '累计变化值', unit: 'mm/m'},
    I4A5: {name: '连续n小时累积变化量', unit: 'mm/m'},
  },
  H1: {
    H1A1: {name: '连续n天平均速度', unit: 'mm/d'},
    H1A2: {name: '单日最大变化量', unit: 'mm'},
    H1A3: {name: '单次最大变化量', unit: 'mm'},
    H1A4: {name: '累计变化值', unit: 'mm'},
    H1A5: {name: '连续n小时累积变化量', unit: 'mm'},
  },
  SG: {
    H1A1: {name: '连续n天平均速度', unit: 'mm/d'},
    H1A2: {name: '单日最大变化量', unit: 'mm'},
    H1A3: {name: '单次最大变化量', unit: 'mm'},
    H1A4: {name: '累计变化值', unit: 'mm'},
    H1A5: {name: '连续n小时累积变化量', unit: 'mm'},
  },
  MD1: {
    // MD1A1: {name: '连续n天平均速度', unit: 'mm/d'},
    // MD1A2: {name: '单日最大变化量', unit: 'mm'},
    MD1A3: {name: '单次最大变化量', unit: 'mm'},
    MD1A4: {name: '累计变化值', unit: 'mm'},
    // MD1A5: {name: '连续n小时累积变化量', unit: 'mm'},
  },
  MH2: {
    // MH2A1: {name: '连续n天平均速度', unit: 'mm/d'},
    // MH2A2: {name: '单日最大变化量', unit: 'mm'},
    MH2A3: {name: '单次最大变化量', unit: 'mm'},
    MH2A4: {name: '累计变化值', unit: 'mm'},
    // MH2A5: {name: '连续n小时累积变化量', unit: 'mm'},
  },
  MVM: {
    // MVMA1: {name: '连续n天平均速度', unit: 'mm/d'},
    // MVMA2: {name: '单日最大变化量', unit: 'mm'},
    MVMA3: {name: '单次最大变化量', unit: 'mm'},
    MVMA4: {name: '累计变化值', unit: 'mm'},
    // MVMA5: {name: '连续n小时累积变化量', unit: 'mm'},
  },
  AICM: {
    A1A1: {name: '连续n天平均速度', unit: 'mm/m/d'},
    A1A2: {name: '单日最大变化量', unit: 'mm/m'},
    A1A3: {name: '单次最大变化量', unit: 'mm/m'},
    A1A4: {name: '累计变化值', unit: 'mm/m'},
    A1A5: {name: '连续n小时累积变化量', unit: 'mm/m'},
  },
}
// export const ALARM_TYPES = {
//   S1: {
//     S1A1: {name: '连续n天，合角度平均速度', unit: '°/d'},
//     S1A2: {name: '单日最大合角度变化量', unit: '°'},
//     S1A3: {name: '合角度变化量', unit: '°'},
//     S1A4: {name: '单次最大合角度变化量', unit: '°'},
//     S1A5: {name: '连续n小时最大变化量', unit: '°'},
//   },
//   S2: {
//     S2A1: {name: '连续n天，合角度平均速度', unit: '°/d'},
//     S2A2: {name: '单日最大合角度变化量', unit: '°'},
//     S2A3: {name: '合角度变化量', unit: '°'},
//     S2A4: {name: '单次最大合角度变化量', unit: '°'},
//     S2A5: {name: '连续n小时最大变化量', unit: '°'},
//   },
//   D1: {
//     D1A1: {name: '连续n天，位移平均速度', unit: 'mm/d'},
//     D1A2: {name: '单日最大位移变化量', unit: 'mm'},
//     D1A3: {name: '合位移变化量', unit: 'mm'},
//     D1A4: {name: '单次最大位移变化量', unit: 'mm'},
//     D1A5: {name: '连续n小时最大变化量', unit: 'mm'},
//   },
//   D2: {
//     D2A1: {name: '连续n天，位移平均速度', unit: 'mm/d'},
//     D2A2: {name: '单日最大位移变化量', unit: 'mm'},
//     D2A3: {name: '合位移变化量', unit: 'mm'},
//     D2A4: {name: '单次最大位移变化量', unit: 'mm'},
//     D2A5: {name: '连续n小时最大变化量', unit: 'mm'},
//   },
//   D3: {
//     D3A1: {name: '连续n天，位移平均速度', unit: 'mm/d'},
//     D3A2: {name: '单日最大位移变化量', unit: 'mm'},
//     D3A3: {name: '合位移变化量', unit: 'mm'},
//     D3A4: {name: '单次最大位移变化量', unit: 'mm'},
//     D3A5: {name: '连续n小时最大变化量', unit: 'mm'},
//   },
//   I1: {
//     I1A1: {name: '连续n天，倾斜度平均速度', unit: 'mm/m/d'},
//     I1A2: {name: '单日最大倾斜度变化量', unit: 'mm/m'},
//     I1A3: {name: '倾斜度变化量', unit: 'mm/m'},
//     I1A4: {name: '单次最大倾斜度变化量', unit: 'mm/m'},
//     I1A5: {name: '连续n小时最大变化量', unit: 'mm/m'},
//   },
//   I2: {
//     I2A1: {name: '连续n天，倾斜度平均速度', unit: 'mm/m/d'},
//     I2A2: {name: '单日最大倾斜度变化量', unit: 'mm/m'},
//     I2A3: {name: '倾斜度变化量', unit: 'mm/m'},
//     I2A4: {name: '单次最大倾斜度变化量', unit: 'mm/m'},
//     I2A5: {name: '连续n小时最大变化量', unit: 'mm/m'},
//   },
//   I3: {
//     I3A1: {name: '连续n天，倾斜度平均速度', unit: 'mm/m/d'},
//     I3A2: {name: '单日最大倾斜度变化量', unit: 'mm/m'},
//     I3A3: {name: '倾斜度变化量', unit: 'mm/m'},
//     I3A4: {name: '单次最大倾斜度变化量', unit: 'mm/m'},
//     I3A5: {name: '连续n小时最大变化量', unit: 'mm/m'},
//   },
//   H1: {
//     H1A1: {name: '连续n天，位移平均速度', unit: 'mm/d'},
//     H1A2: {name: '单日最大位移变化量', unit: 'mm'},
//     H1A3: {name: '累积位移变化量', unit: 'mm'},
//     H1A4: {name: '单次最大位移变化量', unit: 'mm'},
//     H1A5: {name: '连续n小时最大变化量', unit: 'mm'},
//   },
//   MD1: {
//     MD1A1: {name: '连续n天，位移平均速度', unit: 'mm/d'},
//     MD1A2: {name: '单日最大位移变化量', unit: 'mm'},
//     MD1A3: {name: '累积位移变化量', unit: 'mm'},
//     MD1A4: {name: '单次最大位移变化量', unit: 'mm'},
//     MD1A5: {name: '连续n小时最大变化量', unit: 'mm'},
//   },
//   MH2: {
//     MH2A1: {name: '连续n天，位移平均速度', unit: 'mm/d'},
//     MH2A2: {name: '单日最大位移变化量', unit: 'mm'},
//     MH2A3: {name: '累积位移变化量', unit: 'mm'},
//     MH2A4: {name: '单次最大位移变化量', unit: 'mm'},
//     MH2A5: {name: '连续n小时最大变化量', unit: 'mm'},
//   },
//   MVM: {
//     MVMA1: {name: '连续n天，位移平均速度', unit: 'mm/d'},
//     MVMA2: {name: '单日最大位移变化量', unit: 'mm'},
//     MVMA3: {name: '累积位移变化量', unit: 'mm'},
//     MVMA4: {name: '单次最大位移变化量', unit: 'mm'},
//     MVMA5: {name: '连续n小时最大变化量', unit: 'mm'},
//   },
// }

export const THRESHOLD_UNIT = {
  'D': '天',
  'B': '次',
  'H': '小时',
}
